#include "audiographicstrack.h"
#include "audiosceneclip.h"

#include "../core/gridmanager.h"
AudioGraphicsTrack::AudioGraphicsTrack(int index, qreal x, qreal y, qreal width, qreal height,
                                       QPen& pen, QBrush& brush, Core::BaseTrack* trackData, QGraphicsItem *parent) :
    BaseGraphicsTrack(index, x, y, width, height, pen, brush, trackData, parent) {

}
void AudioGraphicsTrack::syncWithTrack() {
    Core::GridManager& manager = Core::GridManager::instance();

    if(auto audio = dynamic_cast<Audio::AudioTrack*>(m_data)) {

        const std::vector<Audio::AudioClip>& clips = audio->getSampler().clips();
        for(const auto& clip: clips) {

            // Calculate the x start position
            // And the length of the clip
            // The height is auto generated by the height of the track.
            // We can pass the audio scene clip the clip as m_data;
            //
            qreal x = manager.ticksToXPos(clip.globalStartTick, 1.0, 0.0);
            qreal y = 25;
            qreal width = manager.ticksToXPos(clip.getTotalTicks(), 1.0, 0.0);
            qreal height = this->rect().height();
            std::shared_ptr<const Audio::AudioClip> _clip = std::make_shared<const Audio::AudioClip>(clip);
            Graphics::BaseSceneClip* newClip = new Graphics::AudioSceneClip(x,y,width, height,m_color, _clip, this);
            m_clips.push_back(newClip);
        }
    }
}
void AudioGraphicsTrack::drawContent(QPainter* painter) {
}
